version: '3.9'
services:
  app:
    container_name: '${APP_NAME:-pbboard}_app'
    build: ./docker
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - .:/var/www/html
    networks:
      - pbboard
    depends_on:
      - mysql

  mysql:
    container_name: '${APP_NAME:-pbboard}_mysql'
    restart: always
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-password}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE:-pbboard}'
      MYSQL_USER: '${DB_USERNAME:-pbboard}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-password}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - './docker/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './docker/mysql:/var/lib/mysql'
    networks:
      - pbboard
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD:-password}"]
      retries: 3
      timeout: 5s

  phpmyadmin:
    platform: linux/x86_64
    restart: always
    container_name: '${APP_NAME:-pbboard}_phpmyadmin'
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:mysql
    ports:
      - '${PHPMYADMIN_PORT:-8080}:80'
    environment:
      MYSQL_USERNAME: '${DB_USERNAME:-pbboard}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-password}'
      PMA_HOST: mysql
    networks:
      - pbboard

networks:
  pbboard:
    driver: bridge

volumes:
  pbboard-mysql:
    driver: local